<?php

namespace Odder\LighthouseScalars\Concerns;

trait ValidatesCurrencyCode
{
    private array $validCurrencyCodes = [
        'ALL' => True,
        'AFN' => True,
        'ARS' => True,
        'AWG' => True,
        'AUD' => True,
        'AZN' => True,
        'BSD' => True,
        'BBD' => True,
        'BDT' => True,
        'BYR' => True,
        'BZD' => True,
        'BMD' => True,
        'BOB' => True,
        'BAM' => True,
        'BWP' => True,
        'BGN' => True,
        'BRL' => True,
        'BND' => True,
        'KHR' => True,
        'CAD' => True,
        'KYD' => True,
        'CLP' => True,
        'CNY' => True,
        'COP' => True,
        'CRC' => True,
        'HRK' => True,
        'CUP' => True,
        'CZK' => True,
        'DKK' => True,
        'DOP' => True,
        'XCD' => True,
        'EGP' => True,
        'SVC' => True,
        'EEK' => True,
        'EUR' => True,
        'FKP' => True,
        'FJD' => True,
        'GHC' => True,
        'GIP' => True,
        'GTQ' => True,
        'GGP' => True,
        'GYD' => True,
        'HNL' => True,
        'HKD' => True,
        'HUF' => True,
        'ISK' => True,
        'INR' => True,
        'IDR' => True,
        'IRR' => True,
        'IMP' => True,
        'ILS' => True,
        'JMD' => True,
        'JPY' => True,
        'JEP' => True,
        'KZT' => True,
        'KPW' => True,
        'KRW' => True,
        'KGS' => True,
        'LAK' => True,
        'LVL' => True,
        'LBP' => True,
        'LRD' => True,
        'LTL' => True,
        'MKD' => True,
        'MYR' => True,
        'MUR' => True,
        'MXN' => True,
        'MNT' => True,
        'MZN' => True,
        'NAD' => True,
        'NPR' => True,
        'ANG' => True,
        'NZD' => True,
        'NIO' => True,
        'NGN' => True,
        'NOK' => True,
        'OMR' => True,
        'PKR' => True,
        'PAB' => True,
        'PYG' => True,
        'PEN' => True,
        'PHP' => True,
        'PLN' => True,
        'QAR' => True,
        'RON' => True,
        'RUB' => True,
        'SHP' => True,
        'SAR' => True,
        'RSD' => True,
        'SCR' => True,
        'SGD' => True,
        'SBD' => True,
        'SOS' => True,
        'ZAR' => True,
        'LKR' => True,
        'SEK' => True,
        'CHF' => True,
        'SRD' => True,
        'SYP' => True,
        'TWD' => True,
        'THB' => True,
        'TTD' => True,
        'TRY' => True,
        'TRL' => True,
        'TVD' => True,
        'UAH' => True,
        'GBP' => True,
        'USD' => True,
        'UYU' => True,
        'UZS' => True,
        'VEF' => True,
        'VND' => True,
        'YER' => True,
        'ZWD' => True,
    ];

    public function isValidCurrencyCode(string $code): bool
    {
        return isset($this->validCurrencyCodes[$code]);
    }
}
