name: CI/CD
on:
  pull_request:
  push:
    branches: 
      - "*"
    tags:
      - "*"

jobs:
  tests:
    name: Generate Code Coverage and upload to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up php 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer self-update && composer install && composer dump-autoload
      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  update-gh-pages:
    name: Generate and upload new GitHub Pages
    runs-on: ubuntu-latest
    concurrency: github-pages
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run action
        uses: ldeluigi/markdown-docs@latest
        with:
          src: ./docs
          dst: ./generated_docs
          title: Lighthouse Scalars
          language: en
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated_docs
